### ISSUE TITLE
IllegalStateException or MissingContextVariableException on use with Jenkins scripted pipeline

### ISSUE THREAD

**Issue by tivervac** [digicert/digicert-software-trust-code-sign-plugin#17]
We have a Jenkins 2.414.2 setup with the master running on Linux that can spawn agents on Linux or Windows on the fly. I want to use the Digicert Jenkins `Code signing with Software Trust Manager Version: 13.v147276d96cb_1` to jarsign on Linux and sign `.exe`s on Windows.

To do so I installed the plugin on our Jenkins and followed [your guide](https://docs.digicert.com/en/software-trust-manager/ci-cd-integrations/plugins/jenkins-plugin-for-keypair-signing.html). The guide mentions we should call `SoftwareTrustManagerSetup()` in the Jenkinsfile. I've tried doing so on both a Linux and Windows agent, but those give me the IllegalStateException shown below. Doing so straight on the master node gives me the MissingContextVariableException.

```
java.lang.IllegalStateException: Jenkins.instance is missing. Read the documentation of Jenkins.getInstanceOrNull to see what you are doing wrong.
    at jenkins.model.Jenkins.get(Jenkins.java:816)
    at io.jenkins.plugins.digicert.AgentInfo.getCredential(AgentInfo.java:45)
    at io.jenkins.plugins.digicert.AgentInfo.getValue(AgentInfo.java:51)
    at io.jenkins.plugins.digicert.AgentInfo.call(AgentInfo.java:64)
    at io.jenkins.plugins.digicert.AgentInfo.call(AgentInfo.java:25)
    at hudson.remoting.UserRequest.perform(UserRequest.java:211)
    at hudson.remoting.UserRequest.perform(UserRequest.java:54)
    at hudson.remoting.Request$2.run(Request.java:377)
    at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:840)
```

```
org.jenkinsci.plugins.workflow.steps.MissingContextVariableException: Required context class hudson.FilePath is missing
Perhaps you forgot to surround the code with a step that provides this, such as: node
    at org.jenkinsci.plugins.credentialsbinding.impl.BindingStep$Execution2.doStart(BindingStep.java:130)
    at org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution.lambda$run$0(GeneralNonBlockingStepExecution.java:77)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
```

The documentation for `Jenkins.getInstanceOrNull` and `Jenkins.get` does indeed mention that this only works on the master node. If this plugin really needs to run on the master node, on a Windows machine, to sign `.exe`s, it is a no-go for us.

**Comment by nixsec** [comment]
I'm seeing a similar issue for https://github.com/jenkinsci/digicert-software-trust-code-sign-plugin which is forked from here.

**Comment by nixsec** [comment]
Seeing a similar issue - https://github.com/digicert/digicert-software-trust-code-sign-plugin/issues/18
